name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: 'macos'
            image: 'macos-12'
          - name: 'linux'
            image: 'ubuntu-22.04'
          - name: 'windows'
            image: 'windows-2022'
            
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.image }}

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - uses: actions/checkout@v3
      - name: NuGet cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
